### ISSUE TITLE
how to use in termux?

### ISSUE THREAD

**Issue by johnredfield2099** [holographicSol/pdfDrive#1]
can you tell me how to use this in termux , 
I want download bulk ebook from pdfdrive.
thanks .

**Comment by holographicSol** [comment]
Fantastic question and I love Termux. Currently pdfDrive is untested on Termux but I will look into it today and get right back to you. Sometimes only minor tweaks if any are necessary to get things operational on a different platform.
Also, if you have already resolved this issue please let me know, thanks!

**Comment by holographicSol** [comment]
Okay I have updated pdfDrive.py to work in Termux. I recommend turning the droid on its side for a better viewing experience.

  In Termux application:
  1. git clone https://github.com/holographicSol/pdfDrive
  2. cd ./pdfDrive
  3. ./requirements.sh
  4. python ./pdfDrive.py -h

Hope this helps!

**Comment by johnredfield2099** [comment]
thanks you very much , it works.

**Comment by holographicSol** [comment]
Excellent, your absolutely welcome. Any issues and feel free to let me know

**Comment by holographicSol** [comment]
I will close this thread now if I may as the issue appears to be resolved. Also, I keep the requirements.sh and .bat pretty up to date to install dependencies automatically, to do this you can run 
requirements.sh from the command line in termux.
Hope this helps
